# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "202db42c098da04ff196f0aa16f74cf4"
name = "Sociall"
application_url = "https://auto-app-rouge.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sociall-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://auto-app-rouge.vercel.app/auth/callback",
  "https://auto-app-rouge.vercel.app/auth/shopify/callback",
  "https://auto-app-rouge.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
