# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c1e2bab4aedc9e2927dbc4852b0cc46"
name = "Sociall-Dev"
application_url = "https://gbp-periods-compiled-yea.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sociall-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://gbp-periods-compiled-yea.trycloudflare.com/auth/callback",
  "https://gbp-periods-compiled-yea.trycloudflare.com/auth/shopify/callback",
  "https://gbp-periods-compiled-yea.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
